// <auto-generated />
namespace Prac2mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedatatypeofbookidfrominttostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedatatypeofbookidfrominttostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201709050737071_change data type of bookid from int to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
