//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC3.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService2")]
    public interface IService2 {
        
        // CODEGEN: Generating message contract since the wrapper name (BookPurchaseInfo) of message BookPurchaseInfo does not match the default value (PurchaseBooks)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/PurchaseBooks", ReplyAction="http://tempuri.org/IService2/PurchaseBooksResponse")]
        MVC3.ServiceReference2.BookPurchaseResponse PurchaseBooks(MVC3.ServiceReference2.BookPurchaseInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/PurchaseBooks", ReplyAction="http://tempuri.org/IService2/PurchaseBooksResponse")]
        System.Threading.Tasks.Task<MVC3.ServiceReference2.BookPurchaseResponse> PurchaseBooksAsync(MVC3.ServiceReference2.BookPurchaseInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookPurchaseInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookPurchaseInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double budget;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.Dictionary<int, int> items;
        
        public BookPurchaseInfo() {
        }
        
        public BookPurchaseInfo(double budget, System.Collections.Generic.Dictionary<int, int> items) {
            this.budget = budget;
            this.items = items;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookPurchaseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookPurchaseResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string response;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public bool result;
        
        public BookPurchaseResponse() {
        }
        
        public BookPurchaseResponse(string response, bool result) {
            this.response = response;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : MVC3.ServiceReference2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<MVC3.ServiceReference2.IService2>, MVC3.ServiceReference2.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC3.ServiceReference2.BookPurchaseResponse MVC3.ServiceReference2.IService2.PurchaseBooks(MVC3.ServiceReference2.BookPurchaseInfo request) {
            return base.Channel.PurchaseBooks(request);
        }
        
        public string PurchaseBooks(double budget, System.Collections.Generic.Dictionary<int, int> items, out bool result) {
            MVC3.ServiceReference2.BookPurchaseInfo inValue = new MVC3.ServiceReference2.BookPurchaseInfo();
            inValue.budget = budget;
            inValue.items = items;
            MVC3.ServiceReference2.BookPurchaseResponse retVal = ((MVC3.ServiceReference2.IService2)(this)).PurchaseBooks(inValue);
            result = retVal.result;
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC3.ServiceReference2.BookPurchaseResponse> MVC3.ServiceReference2.IService2.PurchaseBooksAsync(MVC3.ServiceReference2.BookPurchaseInfo request) {
            return base.Channel.PurchaseBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC3.ServiceReference2.BookPurchaseResponse> PurchaseBooksAsync(double budget, System.Collections.Generic.Dictionary<int, int> items) {
            MVC3.ServiceReference2.BookPurchaseInfo inValue = new MVC3.ServiceReference2.BookPurchaseInfo();
            inValue.budget = budget;
            inValue.items = items;
            return ((MVC3.ServiceReference2.IService2)(this)).PurchaseBooksAsync(inValue);
        }
    }
}
